/*
 * lcd_hd44780_special_chars.h
 *
 *  Created on: Dec 12, 2018
 *      Author: dsolano
 */

#ifndef INC_TEXT_LCD_LCD_HD44780_SPECIAL_CHARS_H_
#define INC_TEXT_LCD_LCD_HD44780_SPECIAL_CHARS_H_
#include <stdint.h>
#include <GenericTypeDefs.h>

//Font Generated by MikroElektronika GLCD Font Creator 1.2.0.0
//MikroeElektronika 2011
//http://www.mikroe.com

//HD44780 Alpha Numeric Character Set - FontName : RTC5x8
//HD44780 Alpha Numeric Character Set - FontSize : 5 x 8

const uint8_t SPECIAL_CHARS[] = {
    0x08, 0x14, 0x08, 0x03, 0x04, 0x07, 0x04, 0x04, // Code for char num #0 - Faranheit
    0x08, 0x14, 0x08, 0x03, 0x04, 0x04, 0x03, 0x00, // Code for char num #1 - Celcius
    0x04, 0x0A, 0x0E, 0x0A, 0x00, 0x1A, 0x15, 0x15, // Code for char num #2 - AM
    0x04, 0x0A, 0x0C, 0x08, 0x00, 0x1A, 0x15, 0x15, // Code for char num #3 - PM
    0x0C, 0x12, 0x12, 0x0C, 0x00, 0x00, 0x00, 0x00, // Code for char num #4 - Degrees
    0x00, 0x01, 0x01, 0x05, 0x05, 0x15, 0x15, 0x00, // Code for char num #5 - Bar
    0x00, 0x15, 0x0E, 0x04, 0x04, 0x04, 0x04, 0x00, // Code for char num #6 - Antenna
    0x0E, 0x1F, 0x1F, 0x1F, 0x1F, 0x1F, 0x1F, 0x00, // Code for char num #7 - Battery Full
    0x02, 0x05, 0x01, 0x12, 0x07, 0x13, 0x14, 0x13, // Code for char num #8 - i2c
    0x04, 0x0E, 0x0E, 0x0E, 0x0E, 0x1F, 0x00, 0x04, // Code for char num #9 - Bell
    0x1C, 0x14, 0x1C, 0x0E, 0x0B, 0x0E, 0x03, 0x02, // Code for char num #10 - Off
    0x1C, 0x14, 0x1C, 0x00, 0x12, 0x1A, 0x16, 0x00, // Code for char num #11 - On
    0x01, 0x03, 0x05, 0x09, 0x09, 0x0B, 0x1B, 0x18, // Code for char num #12 - Music
    0x00, 0x0A, 0x1F, 0x1F, 0x1F, 0x0E, 0x04, 0x00, // Code for char num #13 - Heart
    0x04, 0x0E, 0x1F, 0x04, 0x04, 0x04, 0x04, 0x00, // Code for char num #14 - Up
    0x04, 0x04, 0x04, 0x04, 0x1F, 0x0E, 0x04, 0x00, // Code for char num #15 - Down
	0x01, 0x01, 0x05, 0x0D, 0x1F, 0x0C, 0x04, 0x00, // Code for char num #16 - Enter Key
    0x14, 0x1C, 0x14, 0x00, 0x06, 0x05, 0x06, 0x05  // Code for char num #17 - Humedad relativa
};

#define LCD_SPC_CHAR_POS_0		0
#define LCD_SPC_CHAR_POS_1		1
#define LCD_SPC_CHAR_POS_2		2
#define LCD_SPC_CHAR_POS_3		3
#define LCD_SPC_CHAR_POS_4		4
#define LCD_SPC_CHAR_POS_5		5
#define LCD_SPC_CHAR_POS_6		6
#define LCD_SPC_CHAR_POS_7		7


#define CHARSxLINE				8

#define SPC_CHAR_FARENHEIT		0*CHARSxLINE
#define SPC_CHAR_CELSIUS		1*CHARSxLINE
#define SPC_CHAR_AM				2*CHARSxLINE
#define SPC_CHAR_PM				3*CHARSxLINE
#define SPC_CHAR_DEGREES		4*CHARSxLINE
#define SPC_CHAR_BAR			5*CHARSxLINE
#define SPC_CHAR_ANTENNA		6*CHARSxLINE
#define SPC_CHAR_BATT_FULL		7*CHARSxLINE
#define SPC_CHAR_I2C			8*CHARSxLINE
#define SPC_CHAR_BELL			9*CHARSxLINE
#define SPC_CHAR_OFF			10*CHARSxLINE
#define SPC_CHAR_ON				11*CHARSxLINE
#define SPC_CHAR_MUSIC			12*CHARSxLINE
#define SPC_CHAR_HEART			13*CHARSxLINE
#define SPC_CHAR_UP				14*CHARSxLINE
#define SPC_CHAR_DOWN			15*CHARSxLINE
#define SPC_CHAR_ENTER_KEY		16*CHARSxLINE
#define SPC_CHAR_HUMEDAD_R		17*CHARSxLINE





#endif /* INC_TEXT_LCD_LCD_HD44780_SPECIAL_CHARS_H_ */
